### ISSUE TITLE
Building lunatic-python on windows is complicated

### ISSUE THREAD

**Issue by iljau** [bastibe/lunatic-python#23]
_(rewrote original report to make it readable)_

Question about ["Errors compiling lunatic-python"](http://stackoverflow.com/q/21268706/2419207) appeared on stackoverflow and tried guide affected person through the process: http://stackoverflow.com/a/21283464/2419207

As you can see it's rather long and complicated.

There are some changes, that I did apply to `setup.py` in order to get it working under windows: https://github.com/iljau/lunatic-python/compare/bastibe:master...master

And finally I got to the point where examples provided in ["Lua inside Python"](http://labix.org/lunatic-python#head-754f1a340baa86da36ce0edb8ff8cb396d5be73f) mostly worked.

I hope all previous will serve as a somewhat useful starting point to somebody, who will have time and interest to actually make working windows build.

**Comment by bobombolo** [comment]
would it be helpful for someone to make a CMakeLists.txt so that building with cmake is easy?

**Comment by greatwolf** [comment]
Doesn't this commit do just that? #9
