### ISSUE TITLE
Cannot get lunatic-python to work

### ISSUE THREAD

**Issue by Serilum** [bastibe/lunatic-python#28]
Hi! I am trying to run my python script inside a lua script, however running a simple example I come across this error:
# lua main.lua

lua: main.lua:2: module 'python' not found:
        no field package.preload['python']
        no file '/usr/local/share/lua/5.2/python.lua'
        no file '/usr/local/share/lua/5.2/python/init.lua'
        no file '/usr/local/lib/lua/5.2/python.lua'
        no file '/usr/local/lib/lua/5.2/python/init.lua'
        no file './python.lua'
        no file '/usr/share/lua/5.2/python.lua'
        no file '/usr/share/lua/5.2/python/init.lua'
        no file './python.lua'
        no file '/usr/local/lib/lua/5.2/python.so'
        no file '/usr/lib/arm-linux-gnueabihf/lua/5.2/python.so'
        no file '/usr/lib/lua/5.2/python.so'
        no file '/usr/local/lib/lua/5.2/loadall.so'
        no file './python.so'
stack traceback:
        [C]: in function 'require'
        main.lua:2: in main chunk
        [C]: in ?

With the lua script:

-- main.lua
py = require 'python'

sum_from_python = py.import "sum".sum_from_python
print( sum_from_python(2,3) )

And the python script:

def sum_from_python(a, b):
  return a + b

Any ideas? Thanks!

**Comment by Serilum** [comment]
Running the test.py gives this error:
----- import lua -----
----- lg = lua.globals() -----
lg: <Lua table at 0x199ad68>
lg._G: <Lua table at 0x199ad68>
lg['_G']: <Lua table at 0x199ad68>
----- lg.foo = "bar" -----
----- lg.tmp = [] -----
----- print lg.tmp -----
[]
----- lua.execute("xxx = {1,2,3,foo={4,5}}") -----
----- print lg.xxx[1] -----
1
----- print lg.xxx[2] -----
2
----- print lg.xxx[3] -----
3
----- print lg.xxx['foo'][1] -----
4
lua.require = <built-in function require>
lua.require('foo') raised an exception

**Comment by greatwolf** [comment]
It looks like lua can't locate the lunatic module in your current environment. How did you install and setup lunatic? Did you build it from this repo using cmake?

**Comment by greatwolf** [comment]
closing this issue since there's no response from OP.
