### ISSUE TITLE
Issue with numpy

### ISSUE THREAD

**Issue by mys007** [bastibe/lunatic-python#29]
I encountered two issues when I tried to use numpy from Lua. I use Ubuntu 14.04, Python 2.7 and luajit.

1) Lunatic hadn't compiled until I added -fPIC to CMAKE_C_FLAGS

2) The call `require "python"; python.execute("import numpy as np")` in Lua failed with `ImportError: /usr/lib/python2.7/dist-packages/numpy/core/multiarray.so: undefined symbol: PyExc_SystemError`. Inspired by http://stackoverflow.com/questions/8361437/linker-error-lunatic-python-lua-requiresocket-undefined-symbol-lua-getme I put `#include <dlfcn.h>` to `pythoninlua.c` and added `dlopen("libpython2.7.so.1", RTLD_LAZY | RTLD_GLOBAL);` at the beginning of `LUA_API int luaopen_python(lua_State *L)`. This fixed it. I am wondering if it would be a general improvement?

**Comment by korkinof** [comment]
Was this not merged into the code, because I am being plagued by the same issue.

**Comment by mys007** [comment]
On a bit related note, I just used https://github.com/facebook/fblualib/blob/master/fblualib/python/README.md in the end for my purposes. Your application may differ though.

**Comment by korkinof** [comment]
Yeah, many thanks! I tried fb.python before, but it crashes badly...
I'm getting a message of incompatible folly version 35, when version 34 is needed, so it asks me to downgrade.
I have raised the issue in fblualib...

**Comment by mys007** [comment]
Yes, all the FB dependencies are bit painful, but I was lucky:).

**Comment by greatwolf** [comment]
Just merged the PR #37 for this in. It should fix the undefined symbol problem.
