### ISSUE TITLE
undefined symbol _Py_ZeroStruct

### ISSUE THREAD

**Issue by bobombolo** [bastibe/lunatic-python#35]
I have managed to build the package available from https://pypi.python.org/pypi/lunatic-python-bugfix/1.1.1 but downloading the zip from github on this repo did not build for me (i'm on ubuntu 15.04). anyway, once built, I did <pre>sudo make install</pre> and that worked. I do not know where to go from here. In the original lunatic there was a python.lua file in the main tar.bz2 file (https://pypi.python.org/pypi/lunatic-python/1.0) to load the module but when I call that from my lua script it can't load. Here is the code I am trying to load it with

mymodule.lua:
<pre>
package.path = (PATH.."/lunatic-python-bugfix-1.1.1/?.lua;"..package.path)
local python = require "python"
</pre>

python.lua (copied from lunatic 1.0 release and modified):
<pre>
local path = "/usr/lib/python2.7/site-packages"
if path then
	func = package.loadlib(path.."/lua-python.so", "luaopen_python")
	if func then
		func()
		return
	end
end
if not loaded then
	error("unable to find python module")
end
</pre>
i have also replaced "luaopen_python" with "lua" and "lua-python" but neither work, "loaded" remains nil. I tried those two because of the output from make install:
<pre>
python setup.py install \
	--root=/ \
	--prefix=/usr \
	--install-scripts=/usr/bin
running install
running build
running build_ext
running install_lib
creating /usr/lib/python2.7/site-packages
copying build/lib.linux-x86_64-2.7/lua.so -> /usr/lib/python2.7/site-packages
copying build/lib.linux-x86_64-2.7/lua-python.so -> /usr/lib/python2.7/site-packages
running install_egg_info
Writing /usr/lib/python2.7/site-packages/lunatic_python_bugfix-1.1.1-py2.7.egg-info
</pre>
any suggestions on what to try next to get lunatic loaded into my lua script? by the way my script is using an embedded instance of lua 5.1 that comes with minetest.

**Comment by greatwolf** [comment]
Have you tried building it with CMake? It worked for me last time I tried it under windows and linuxlite. The build should produce two binaries, `python.dll` and `lua.pyd`, for requiring in lua and importing in python respectively. They're the same binary but with the name and extension changed so the modules import correctly.

Note the entry point lua looks for when requiring the module is `luaopen_python` so you don't want to change that. Python looks for `PyInit_lua` when importing.

**Comment by bobombolo** [comment]
the file /usr/lib/python2.7/site-packages/lua-python.so exists so the build worked, no?

doing:
<pre>
assert(package.loadlib("/usr/lib/python2.7/site-packages/lua-python.so", "luaopen_python"))
</pre>gives the error:
<pre>.../mods/realterrain/lunatic-python-bugfix-1.1.1/python.lua:3: /usr/lib/python2.7/site-packages/lua-python.so: undefined symbol: _Py_ZeroStruct</pre>

**Comment by bobombolo** [comment]
i see this may be a duplicate of #17

**Comment by bobombolo** [comment]
output of ldd:
<pre>
ldd /usr/lib/python2.7/site-packages/lua-python.so
	linux-vdso.so.1 =>  (0x00007ffcf7dbf000)
	liblua5.1.so.0 => /usr/lib/x86_64-linux-gnu/liblua5.1.so.0 (0x00007fa36d805000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007fa36d5e5000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fa36d215000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007fa36cf0d000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007fa36cd05000)
	/lib64/ld-linux-x86-64.so.2 (0x00005607afc48000)
</pre>

**Comment by bobombolo** [comment]
ouput of ldd on lua.so:
<pre>

**Comment by bobombolo** [comment]
nevermind the solution in #17 to explicitly load libpython before requiring lunatic worked.
