### ISSUE TITLE
Getting an error "Could NOT find Lua: Found unsuitable version 5.1.4" with lua version 5.2.4

### ISSUE THREAD

**Issue by shehroze37** [bastibe/lunatic-python#38]
Hi 
My current version of lua is 5.2.4 which I can check by using the command lua -v but unfortunately when I manually try to install lunatic-python I get the following error.

CMake Error at /usr/share/cmake-3.5/Modules/FindPackageHandleStandardArgs.cmake:148 (message):
  Could NOT find Lua: Found unsuitable version "5.1.4", but required is at
  least "5.2" (found )
Call Stack (most recent call first):
  /usr/share/cmake-3.5/Modules/FindPackageHandleStandardArgs.cmake:386 (_FPHSA_FAILURE_MESSAGE)
  /usr/share/cmake-3.5/Modules/FindLua.cmake:167 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  CMakeLists.txt:9 (find_package)

-- Configuring incomplete, errors occurred!

I am not sure why its not able to find the lua 5.2.4 ? I would appreciate any help !

Cheers !

**Comment by greatwolf** [comment]
In case you still need help on this, I recently updated the cmake `find_package` to use `Lua` instead of `Lua52`. You can use `-DCMAKE_PREFIX_PATH=*your_lua_path*` to point cmake to the right path to look for your lua install.
