### ISSUE TITLE
Lua 5.1 support

### ISSUE THREAD

**Issue by marcelvanherk** [bastibe/lunatic-python#43]
Hi,

the cmakelists.txt file states that lunatic-python only supports lua5.2 up. However, it compiles and runs OK with lua5.1 under windows as far as I can see. I suggest to change it to 5.1.

To compile it I used a visual 2015 command prompt and entered something like this (paths are specific for my system, I actually use a batch file to compile anything):

cl /Zi /MT /nologo /O2 /W3 /c /D_CRT_SECURE_NO_DEPRECATE /D_WIN32 /arch:AMD64 /IE:\lua_5.1.5\include /IE:\Python27\include luainpython.c pythoninlua.c
link /dll /machine:AMD64 /out:python.dll /export:luaopen_python *.obj lua5.1.lib python27.lib

I then ran my (lua scripted) application from within the python27 folder with the produced python.dll in my clibs folder. 

As a test I ran:

require('python')
python.eval[[{1,2,'a'}]]
np = python.import("numpy") 
a = np.arange(15).reshape(3, 5)

which produced:

set(['a', 1, 2])
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]

Note: python.dll is in my view a misnomer. As it needs to be located in the python folder, it may be better to call it luapython and make line 1 of the test: python = require('luapython') 

Marcel

**Comment by greatwolf** [comment]
When I originally added cmake support I did test it against 5.1 and it was working. It seems like someone changed it to require 5.2 along the way though I'm not sure why.

Agree with the naming of the produced .dll/.so. I'm thinking of naming it something like lunaticpython and lunaticlua instead.

**Comment by marcelvanherk** [comment]
Just to add to the documentation. If you have python.dll in your lua application, make sure PYTHONHOME is set. I used: 

SETX PYTHONHOME e:\python27

Then python can be called from any lua application anywhere

Marcel
