### ISSUE TITLE
Implementing operators possible?

### ISSUE THREAD

**Issue by marcelvanherk** [bastibe/lunatic-python#44]
Hi, testing matplotlib.

    require('python')
    np = python.import("numpy") 
    plt = python.import("matplotlib.pyplot") 
    t = np.arange(1, 10, 0.1)
    s = np.sin(t)
    plt.plot(t, s)
    plt.show()

Works, but I cannot write in line 5

    s = np.sin(2*np.pi*t)

which gives attempt to perform arithmetic on global 't' (a userdata value)

Is there a generic way to solve this?

Marcel

**Comment by greatwolf** [comment]
You could try hooking this into the `__mul` metamethod and just have it defer to running python code and returning the result.

    getmetatable(t).__mul = function (self, n)
      local mul = python.eval "lambda arr, n: arr * n"
      return mul(self, n)
    end

I didn't test this on numpy but trying this on a regular py list does work so it should work with aranges as well. Likewise for the other math operators, see http://lua-users.org/wiki/MetatableEvents for the metamethod names.

If working with a lot of arange objects you'll probably want to wrap the above into a constructor function that automatically attaches the operator metamethods to the newly created instance for convenience.

**Comment by marcelvanherk** [comment]
Hi,

I was thinking of something more generic, i.e., put the equivalent of this code in pythoninlua.c as it would increase its usability.

regards,

Marcel

**Comment by marcelvanherk** [comment]
Hi,

I implemented it as follows:

static int py_object_mul(lua_State *L)
{
    int r=0;
    PyObject *value;
    if (lua_isuserdata(L, 1))
    { py_object *obj = (py_object*) luaL_checkudata(L, 1, POBJECT);
      lua_remove(L, 1);
      value = PyObject_GetAttrString(obj->o, "__mul__");
    }
    else
    { py_object *obj = (py_object*) luaL_checkudata(L, 2, POBJECT);
      lua_remove(L, 2);
      value = PyObject_GetAttrString(obj->o, "__rmul__");
    }
    r = py_object_call2(L, value);
    Py_DECREF(value);
    return r;
}

where py_object_call2 is a copy of py_object_call with the calling object passed explicitly as second parameter. Does this look OK to you? Do you know a more elegant way?

Marcel
