### ISSUE TITLE
Suggestion to change addressing object by number to force asindx access

### ISSUE THREAD

**Issue by marcelvanherk** [bastibe/lunatic-python#45]
Hi,

in this sample:

    require('python')
    np = python.import('numpy')
    a = np.arange(1, 10)

`a[0]` is not defined. It only becomes defined after you say 

    a = python.asindx(a)

I would there like to suggest the following change:

    if (obj->asindx || lua_isnumber(L, 2))
        return _p_object_newindex_set(L, obj, 2, 3);

and

    if (obj->asindx || lua_isnumber(L, 2))
        return _p_object_index_get(L, obj, 2);

This would force every numerical access to be seen as an index access, which simplifies numpy data access from Lua a lot. Does that sound like a good idea?

Marcel

**Comment by greatwolf** [comment]
The index vs attrib access could definitely use some refinement. You can take this further and just check that `lua_type(L, 2) != LUA_TSTRING`. Since attributes are always strings in python, trying to do attribute access using a non-string key is nonsensical.

**Comment by marcelvanherk** [comment]
Hi, not sure that  lua_type(L, 2) != LUA_TSTRING would help much over lua_isnumber; since apart from string and number, we do have some valid table indexes in lua such as function or userdata, but they are very rarely used I believe. But either modification would do.

Marcel

**Comment by greatwolf** [comment]
Yes, this change is just to make it a little more general. Someone else down the line might want to use esoteric lua types as keys and since we're changing this anyway.

**Comment by marcelvanherk** [comment]
OK, will do it like this.

**Comment by greatwolf** [comment]
`lua_isstring(L, 2)` does implicit conversion from a number to a string before performing the check. This is why I used `lua_type` instead so this doesn't happen.

**Comment by marcelvanherk** [comment]
OK, fixed
