### ISSUE TITLE
Can we pass named arguments from Lua to python?

### ISSUE THREAD

**Issue by marcelvanherk** [bastibe/lunatic-python#46]
Hi,

I am trying this sample:

plt.scatter(x, y, c='red')

Which works as is in Lua with the c='red'. A logical way to call this from lua would be:

plt.scatter(x, y, {c='red'})

or

plt.scatter{x, y, c='red'}

but neither work. Is there a way to perform this call, and if not should we add it? I guess a similar question is how a table is passed to python. I guess it could be passed as a dictionary but I cannot find this.

Marcel

**Comment by greatwolf** [comment]
I had a similar idea of supporting keyword arguments but didn't get around to implementing this. I'm leading towards the second form of the syntax. To avoid ambiguities with the way lunatic currently handles py function calls I suggest adding the following requirements:

 - Interpret the py function call parameters as keyword args iff a lua table is given and that is the only parameter given.
 - Corollary is if 0 or > 2 arguments are passed treat it as a regular non-keyword call performing the usual lua->python type conversion as it's currently doing.

The idea is to not take away call possibilities while adding keyword support. For example, say you want to pass a single lua table but not treat it as keywords, you can do `some_pyfunction {{x, y, c = 'red'}}` or `some_pyfunction ({x, y, c = 'red'}, nil)`.

Regarding how lua tables are passed, I believe it's just wrapped as a custom python C object `LuaObject_Type`. This is how lunatic handles types that don't have clean mapping to the other side. This includes lua tables, lua coroutines, lua udata etc. Relevant code [here](https://github.com/bastibe/lunatic-python/blob/master/src/luainpython.c#L92) and [here](https://github.com/bastibe/lunatic-python/blob/master/src/luainpython.c#L176)

**Comment by marcelvanherk** [comment]
Hi,

I agree with you that the second looks cleaner; table members that have a number index (1 etc) could be regular parameters while those with a string index would be named. The exceptions you mentioned make sense, I like your sample some_pyfunction ({x, y, c = 'red'}, nil) more as it then represents a normal call, although {{x, y, c = 'red'}}  would also be valid, as argument[1] would be a table passed as regular parameter in a call that could take named parameters but doesn't. 

Do you know some sample code that builds a call like this in C? I could not easily find one. I assume yours is the latest lunatic python, so it would be good to work this out together.

It is interesting that tables are passed 'opaque'. That means that python can do very little with them. It would be nice to have a way to 'explode - as it is called in lupa' python objects into nested tables and vice versa. Now you have to loop over every element to fill a python object from Lua, say a nparray for plotting.

Marcel

**Comment by marcelvanherk** [comment]
Hi,

thus is how far I got with changing py_object_call - will be testing it soon.

    PyObject* pKywdArgs = NULL;
    if (nargs==1 && lua_istable(L, 2)) {
	pKywdArgs = PyDict_New();    
        lua_pushnil(L);  /* first key */
	i = 1;
        while (lua_next(L, 2) != 0) {
            if (lua_isnumber(L, -2) && lua_tointeger(L, -2)==i) {
	        PyObject *arg = LuaConvert(L, -1);
                if (!arg) {
                    Py_DECREF(args);
                    return luaL_error(L, "failed to convert argument #%d", i);
                    }
		lua_pop(L, 1);
	        PyTuple_SetItem(args, i-1, arg);
		i++;
	    }
	    else if (lua_isstring(L, -1)) {
	        PyObject *arg = LuaConvert(L, -1);
                if (!arg) {
                    Py_DECREF(args);
                    return luaL_error(L, "failed to convert argument '%s'", lua_tostring(L, -1));
                    }
		lua_pop(L, 1);
		PyDict_SetItem(pKywdArgs, lua_tostring(L, -1), arg);
            }
        }
    }
        for (i = 0; i != nargs; i++) {
            PyObject *arg = LuaConvert(L, i+2);
            if (!arg) {
                Py_DECREF(args);
                return luaL_error(L, "failed to convert argument #%d", i+1);
            }
            PyTuple_SetItem(args, i, arg);
       }
    }

    value = PyObject_Call(obj->o, args, pKywdArgs);

**Comment by marcelvanherk** [comment]
and a test program:

require('python'); np = python.import('numpy'); plt = python.import('matplotlib.pyplot')
a=np.arange(0,10); b = a^a
plt.plot{a,b,c='red'}; plt.show()

**Comment by marcelvanherk** [comment]
Code attached.
[pythoninlua.zip](https://github.com/bastibe/lunatic-python/files/644138/pythoninlua.zip)

**Comment by greatwolf** [comment]
Can you submit it as a PR so I can merge it?

**Comment by marcelvanherk** [comment]
Done.

**Comment by marcelvanherk** [comment]
Should have been closed long ago
