### ISSUE TITLE
problem about python in luajit 

### ISSUE THREAD

**Issue by Vogen** [bastibe/lunatic-python#53]
When I use python in luajit, I got screen output as
`--- got low-mem: len=0xfdae1000, start=0x251f000, end=0x100000000`
And this message disappear when using lua.
What does that message mean?

**Comment by greatwolf** [comment]
Can you show a minimal code snippet that reproduces the problem?

**Comment by Vogen** [comment]
@greatwolf  
```
user@host:~$ cat test.lua
python = require "python"
user@host:~$ lua test.lua
user@host:~$ luajit test.lua
--- got low-mem: len=0xfe00f000, start=0x1ff1000, end=0x100000000
```

**Comment by greatwolf** [comment]
What python/luajit version are you using and on what linux OS?

I can't reproduce this tested on linux lite kernel 4.4.0-45-generic. Using luajit-2.0.4 and Python 3.5 seems to work just fine.

**Comment by Vogen** [comment]
Lunatic-python don't lead to this problem.
