### ISSUE TITLE
lua-python import error

### ISSUE THREAD

**Issue by Vogen** [bastibe/lunatic-python#55]
I use `cmake ./` and `make` to build `lua.so` and 'python.so'. And error occur while using.
```
user@host:~$ cat test.lua
python = package.loadlib("/path/to/lunatic-python/bin/lua.so", "luaopen_python")()
python.execute("import os")
python.execute("import multiprocessing")
user@host:~$ lua test.lua
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/lib/python2.7/multiprocessing/__init__.py", line 84, in <module>
    import _multiprocessing
ImportError: /usr/lib/python2.7/lib-dynload/_multiprocessing.x86_64-linux-gnu.so: undefined symbol: _Py_ZeroStruct
```
Actually, I don't know what is the right way to build and to use .so file.

**Comment by greatwolf** [comment]
Try running `package.loadlib` on the python-2.7 runtime first. eg.

    package.loadlib("libpython2.7.so", "*")
    py = require 'python'
   -- ...

That'll force `dlopen` to load the python-2.7 runtime and its symbols globally otherwise when the multiprocess module loads, those python api functions won't be visible. Strangely, Python 3.5 doesn't seem to need this.

**Comment by Vogen** [comment]
@greatwolf  
it doesn't work.
```
usr@host:~$ cat test.lua
package.loadlib("/usr/lib/python2.7/config-x86_64-linux-gnu/libpython2.7.so", "*")
py = require "python"
py.execute("import os")
py.execute("import multiprocessing")

usr@host:~$ lua test.lua
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/lib/python2.7/multiprocessing/__init__.py", line 84, in <module>
    import _multiprocessing
ImportError: /usr/lib/python2.7/lib-dynload/_multiprocessing.x86_64-linux-gnu.so: undefined symbol: _Py_ZeroStruct
```

**Comment by greatwolf** [comment]
Make sure you're running this on at least lua5.2. lua 5.1's `package.loadlib` doesn't support that signature.

**Comment by Vogen** [comment]
Sad, I use lua5.1. How to solve it?

**Comment by greatwolf** [comment]
There's a PR #37 that you could try. I haven't got around to testing it yet so dunno if it works.

**Comment by Vogen** [comment]
I run the code on lua5.2 successfully. And I want to build lunatic-python with luajit source code. Could you give me any advice?

**Comment by greatwolf** [comment]
The rough steps to build on linux are:

 - install luajit with `apt-get`. 
 - install `libluajit-5.1-dev` needed to build lunatic. 
 - install cmake
 - build lunatic using cmake; an out-of-source build is recommended
 - use `-DCMAKE_PREFIX_PATH`, `-DPYTHON_LIBRARY` and `-DLUA_LIBRARY` to point cmake on which lua and python runtime to link against.

For example, the following builds for me on linux lite:

    cmake -B./build -H. -DPYTHON_LIBRARY=/usr/lib/i386-linux-gnu/libpython2.7.so -DLUA_LIBRARY=/usr/lib/i386-linux-gnu/libluajit-5.1.so -DCMAKE_PREFIX_PATH="/usr/include/python2.7;/usr/include/luajit-2.0"
    cmake --build ./build

**Comment by Vogen** [comment]
Thank you @greatwolf , It works!

**Comment by greatwolf** [comment]
no problem. I'm closing this issue unless there's something else.
