### ISSUE TITLE
Can lunatic-python works with Lua 5.3?

### ISSUE THREAD

**Issue by Jayatubi** [bastibe/lunatic-python#57]
Can lunatic-python works with Lua 5.3?

**Comment by greatwolf** [comment]
yes it should, it's been test compiled with lua 5.3 + python 2.7 & 3.6 in [travis CI](https://travis-ci.org/greatwolf/lunatic-python)

**Comment by Jayatubi** [comment]
Alright I made it with a bit works:

1. Since I'm using CentOS 7 and the lua-devel from yum is version 5.1 I have to download the source of 5.3 and compile it myself and add `-fPIC` to the CFALGS is mandatory;
2. After that I need to add a pkg-config file to describe about the newly built includes/libs;
3. Then modify the setup.py to change the Lua version from 5.2 to 5.3.

I'm wondering if there is a simple way to switch lunatic-python's Lua versions.
