### ISSUE TITLE
free on NULL or return without free

### ISSUE THREAD

**Issue by miksyn** [bastibe/lunatic-python#61]
File: luainpython.c; func: Lua_run
In case eval == false - free(NULL)
In case eval == true and luaL_loadbuffer(LuaState, s, len, "<python>") != 0 - no free(buf)

**Comment by greatwolf** [comment]
Good catch, it's one of those annoying things with manually managing memory in C with no RAII.

The first case isn't too bad, `free(NULL)` is okay, will need to fix the second case though.
