### ISSUE TITLE
Support multiple return in from Python

### ISSUE THREAD

**Issue by Togtja** [bastibe/lunatic-python#77]
So I created a python function which looks like this:
```
def double_ret():
    return 1,4
```
and in Lua I expected to be able to do this:

```
a, b = py.import("test_double").double_ret()
```
However, this did not work. As 'a' got a PObject and 'b' became nil. I hope it is possible to support this!

**Comment by greatwolf** [comment]
If I recall correctly, python handles multiple returns by turning it into a tuple. That `PObject` you get back should be a tuple. As a workaround you can write an unpack helper for this. Something like:

    local pylen = py.eval 'len'
    function unpack(tuple, i)
      i = i or -pylen(tuple)
      if i == 0 then return end
      return tuple[i], unpack(tuple, i + 1)
    end

    local double_ret = py.import "test_double"
    a, b = unpack( double_ret() )

**Comment by Togtja** [comment]
Thank you for the suggestion! One more thing I noticed, is it possible to create a "list" in Lua to send to Python.
In Lua I can create a table like so
```
foo = {
    "Text",
   "Text2",
   "etc...."
}
py.func(foo)
```
In python func would be like this:
```
def func(text_list):
    print(text_list)
```
This give me an error about too many arguments to python function, I.E every element in the Lua table is considered an argument. The workaround for this has been to make python function take in a variable amount of argument like so:
```
def func(*text_list):
    for text in text_list:
       print(text)
```
However, I came across an issue if I wanted to input 2 lists of different types, in Lua:
```
foo = {
    "Text",
   "Text2",
   "etc...."
}
bar = {
    1.4,
   2.5,
   3.6
}
py.func(foo,bar)
```

How should this be typed, if possible at all, in Python

**Comment by greatwolf** [comment]
yea this was changed a while back to have this behavior. Lunatic needed a way to pass keyword args from lua to python. The solution used was to represent kwargs as a table from the lua side. Lunatic will treat the lua table as a kwarg list if and only if it's a table *and* it's the only argument.

If you want to pass a lua table to python as a lua table, the two options are to wrap that table in another table or pass `nil` as a second dummy argument.

Examples,

    py.func{foo}
    -- or
    py.func(foo, nil)

There may be a better way to approach this but I haven't had time to revisit it.
